---
  - name: Ensure git is installed
    become: true
    package:
      name: git
      state: present
  - name: install password manager
    become: true
    package:
      name: libsecret-1-0
      state: present
  - name: install password manager dev
    package:
      name: libsecret-1-dev
      state: present
  - name: build the password manager
    become: true
    command: make
    args:
      chdir: /usr/share/doc/git/contrib/credential/libsecret
  - name: change git credential manager
    command: git config --global credential.helper /usr/share/doc/git/contrib/credential/libsecret/git-credential-libsecret