---
- name: Install KVM
  become: true
  package:
    name: qemu-kvm
    state: present
- name: Add user to kvm group
  become: true
  user:
    name: matthias
    groups: kvm
    append: yes
- name: Ensure group "libvirtd" exists
  become: true
  ansible.builtin.group:
    name: libvirtd
    state: present
- name: Add user to libvirtd group
  become: true
  user:
    name: matthias
    groups: libvirtd
    append: yes
- name: Install Qemu
  become: true
  package:
    name: qemu-system-x86
    state: present
- name: Create a symbolic link
  become: true
  ansible.builtin.file:
    src: /usr/bin/qemu-system-x86_64
    dest: /usr/bin/qemu
    owner: root
    group: root
    state: link
- name: Install Qemu Gnome
  become: true
  package:
    name: virt-manager
    state: present
- name: Start service libvirtd, if not started
  ansible.builtin.service:
    name: libvirtd
    state: started
- name: Install Vagrant for Provisioning
  become: true
  package:
    name: vagrant
    state: present